### ISSUE TITLE
Make the oembed the default tag type

### ISSUE THREAD

**Issue by rob-murray** [rob-murray/jekyll-twitter-plugin#12]
This plugin was intended to be able to use any of the Twitter API functions, so the tag arguments are as follows.

```
{% plugin_type api_type *params %}
```

At the moment the need has not arisen for more api types so maybe make the current `oembed` type the default so that you can just do this.

```
{% twitter https://twitter.com/rubygems/status/518821243320287232 %}
```

**Comment by nhoizey** [comment]
+1 ;-)

**Comment by nickjj** [comment]
If anyone is looking to hack this in, the solution below implements it in a way that works:

Replace:

```ruby
    def initialize(_name, params, _tokens)
      super
      @cache    = FileCache.new('./.tweet-cache')
      args      = params.split(/\s+/).map(&:strip)
      @api_type = args.shift
      @params   = args
    end
```

With:

```ruby
    def initialize(_name, params, _tokens)
      super
      @cache    = FileCache.new('./.tweet-cache')
      args      = params.split(/\s+/).map(&:strip)

      if args[0].start_with?('http')
        @api_type = 'oembed'
      else
        @api_type = args.shift
      end

      @params = args
    end
```

I didn't bother making a PR because it looks like an even better solution #16 could be in the works. I just wanted something quick and dirty so I could reference {% twitter %} without supplying `oembed`.

**Comment by rob-murray** [comment]
Great, thanks ...I will take this as a hint and get round to at least adding this default type 😉
