### ISSUE TITLE
Jekyll doesn't recognize Liquid Twitter tag

### ISSUE THREAD

**Issue by YoungLink4** [rob-murray/jekyll-twitter-plugin#30]
I tried to use the plugin using the gemfiles and it works locally on my laptop, but if I try to build the page via GitHub, I just get an error. Can I fix it somehow?

The tag `twitter` on line 1 in `_posts/2017-08-09-Anti-Damone.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.

**Comment by rob-murray** [comment]
Hi,
Sorry but Github does not allow most Jekyll plugins when using Github pages - see [here](https://github.com/github/pages-gem/issues/171) and [here](https://pages.github.com/versions/).

The reason is that they can't run untrusted code in their infrastructure and the workaround is to build it locally and deploy the generated html.
